FROM mongo
RUN ["apt-get", "update", "-y"]
RUN ["apt-get", "install", "-y", "--no-install-recommends", "software-properties-common"]
RUN ["apt-get", "install", "-y", "nano"]
RUN ["apt-get", "install", "-y", "locate"]
